# Generated by Django 5.1.3 on 2024-11-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
