# Generated by Django 5.1.3 on 2024-11-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_text_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
