# Generated by Django 5.1.3 on 2024-11-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_author_id_message_author_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_uuid',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default='dm', max_length=150),
            preserve_default=False,
        ),
    ]
